### PR TITLE
chore(core): improve types

### PR DESCRIPTION
**Pull request by yi-tuan**
Signed-off-by: yi-tuan <1260320217@qq.com>

### CODE REVIEW

**Comment by lachlanjc** [comment]
@hasparus Can you take a look at this?

**Comment by hasparus** [comment]
I prefer the original code for two reasons

1. From user's standpoit: It uses an interface, so there's a shorter tooltip, and shorter eventual error message.
image
image

2. From contributor's standpoint: It's dumber. A big inlined type is easier to wrap your head around than an intersection of mapped type with smaller inlined type.

What's your opinion, @lachlanjc?

**Comment by lachlanjc** [comment]
I don't have enough TypeScript experience to weigh in on this—I understand the basics, but personally don't use TS on any projects, so I'm not sure what should be preferred here. Sorry :)

**Comment by lachlanjc** [comment]
If you don't think this is a big win, I'm totally cool with closing since it's been several months here

**Pull request closed without merging**
