### PR TITLE
Bugfix: remove Paragraph hardcoded style

### LINKED ISSUE #1476: Remove sx props from Paragraph component
https://github.com/system-ui/theme-ui/blob/29b9b37f37b22924c5afe516972acc0c02266d71/packages/components/src/Paragraph.js#L14-L22

While I appreciate the intent, this makes it really tough to use `Paragraph` except for one very specific use case. It takes a specificity hack to defeat it using the theme:

```js
export const theme = {
  text: {
    paragraph: {
      ':not(_)': {
        my: 3,
        maxWidth: 'unset'
      }
    }
  }
}

```

I think the `margin` reset probably belongs in a base theme, and the `maxWidth` is an interesting idea that could be mentioned in the documentation or included in a paragraph variant in one of the themes.

### PR DESCRIPTION
**Pull request by flo-sch**
- fix(components): remove hardcoded Paragraph style
  - remove hardcoded sx props (such style is easy to opt-in with the theme / variants, but harder to opt-out)

Fixes #1476

Ping @atanasster since you commented on the original PR, just for awareness and potential feedback?

### CODE REVIEW

**Comment by lachlanjc** [comment]
Let's absolutely axe the max width, but I think we should keep the margin: 0 we've currently got. Otherwise, as the source comment indicates, you can use a Theme UI component & end up with non-theme spacing from the user agent styles.

**Comment by flo-sch** [comment]
Yeah, also uncertain about the margin...
I'm struggling overall with SoC here, is theme-ui intention to do CSS-reset, or should that be the role of a preset // something else than theme-ui?

In the issue, part of the feedback from @aaronadamsCA is:

> I think the margin reset probably belongs in a base theme

But theme-ui does not have a "base theme", that's its goal actually (not to have one, allowing anyone to provide such base style for their UI)
At the same time, it is trivial to opt in AND out of that margin with the default `paragraph` variant 🤷‍♂️

**Comment by hasparus** [comment]
> you can use a Theme UI component & end up with non-theme spacing from the user agent styles.

Only if you change the variant to one you added, innit? Good to merge from my perspective if I'm not mistaken here.

**Review by hasparus — APPROVED** [review]

**Comment by lachlanjc** [comment]
I'm okay to go along with removing the margin, but I don't think it's worth breaking people's designs with this change, especially because I would see it as a bug in Theme UI that components have default margins that are not coming from my theme

**Comment by flo-sch** [comment]
> Only if you change the variant to one you added, innit?

Not necessarily I think, if you do not inherit a preset setting `margin: 0` on that default variant, and we remove it from the component itself (as this PR currently does), then "Paragraph" rendering a "p" by default would inherit the browser's margin

**Comment by flo-sch** [comment]
Alright, then let's re-add the margin reset, which can easily be opted out by setting whichever margin value on the `text.paragraph` default variant :)

**Review by lachlanjc — APPROVED** [review]

**Comment by hasparus** [comment]
And it's merged! Thanks a lot @flo-sch!

**Comment by vanbujm** [comment]
I have been having trouble overriding the margin style.

Can we change:
```javascript
    <Box
      ref={ref}
      as="p"
      variant="paragraph"
      {...props}
      sx={{
        // reset margin by default: avoid relying on user-agent margins (not aware of theme-ui space scale)
        margin: 0,
        ...sx
      }}
      ...
```

To:
```javascript
    <Box
      ref={ref}
      as="p"
      variant="paragraph"
      sx={{
        // reset margin by default: avoid relying on user-agent margins (not aware of theme-ui space scale)
        margin: 0,
        ...sx
      }}
      {...props}
      ...
```

So that you can use margin props (m, my, mx, etc) to override margin?

**Comment by lachlanjc** [comment]
Seems fine to me @vanbujm! PR welcome

**Comment by vanbujm** [comment]
> Seems fine to me @vanbujm! PR welcome

[PR](https://github.com/system-ui/theme-ui/pull/1658) is up.

**Pull request merged**
