### PR TITLE
docs(jsx-pragma): Add section on using with vite

### PR DESCRIPTION
**Pull request by PeterlitsZo**
For issue #2115.

### CODE REVIEW

**Review by lachlanjc — APPROVED** [review]
Appreciate the addition! Tweaked the language a bit for clarity/grammar.

**Comment by PeterlitsZo** [comment]
Thanks, I get it.

**Comment by hasparus** [comment]
:rocket: PR was released in [`v0.14.0-develop.11`](https://github.com/system-ui/theme-ui/releases/tag/v0.14.0-develop.11) :rocket:

**Comment by hasparus** [comment]
:rocket: PR was released in [`v0.14.0`](https://github.com/system-ui/theme-ui/releases/tag/v0.14.0) :rocket:

**Comment by PeterlitsZo** [comment]
Great!

**Pull request merged**
