### PR TITLE
Update readme, add Discord badge

### PR DESCRIPTION
**Pull request by hasparus**
@lachlanjc @atanasster, how do you like it? Would you change anything?

---

Screenshot:

image

### CODE REVIEW

**Review by lachlanjc — APPROVED** [review]
Looks great, thank you!

**Comment by hasparus** [comment]
I have second thoughts.
image

@lachlanjc @atanasster, isn't this looking better than what we just merged?

**Comment by hasparus** [comment]
current for comparison

image

**Comment by hasparus** [comment]
Okay, I just made a new PR 
https://github.com/system-ui/theme-ui/pull/1303

**Pull request merged**
