### PR TITLE
Update preset-tailwind for Tailwind v3 (breaking)

### PR DESCRIPTION
**Pull request by lachlanjc**
Trying to make it easier to come over from Tailwind by having their latest color palettes etc in our preset!

# Version

Published prerelease version: `v0.15.4-develop.0`

<details>
  <summary>Changelog</summary>

  #### 🐛 Bug Fix
  
  - Update preset-tailwind for Tailwind v3 (breaking) [#2357](https://github.com/system-ui/theme-ui/pull/2357) ([@lachlanjc](https://github.com/lachlanjc))
  
  #### Authors: 1
  
  - Lachlan Campbell ([@lachlanjc](https://github.com/lachlanjc))
</details>

### CODE REVIEW

**Review by hasparus — APPROVED** [review]
LGTM. I love those color palettes.

**Comment by hasparus** [comment]
:rocket: PR was released in [`v0.15.4-develop.0`](https://github.com/system-ui/theme-ui/releases/tag/v0.15.4-develop.0) :rocket:

**Comment by hasparus** [comment]
:rocket: PR was released in [`v0.15.4`](https://github.com/system-ui/theme-ui/releases/tag/v0.15.4) :rocket:

**Comment by LekoArts** [comment]
@hasparus @lachlanjc Why was this released in a patch and not a minor?
I just realized that all my projects are broken :/

**Comment by lachlanjc** [comment]
Oof, sorry about that! Definitely should've been a minor version. @hasparus Is there a doc where I can read about how to control releases?

**Comment by LekoArts** [comment]
No worries, I'll fix it on my end. I had to switch from `@theme-ui/presets` to `@theme-ui/preset-tailwind` tho as the former uses `^` for its versions. So even when I pinned `@theme-ui/presets` it uses the latest individual presets

**Comment by hasparus** [comment]
Super sorry for that, @LekoArts. I totally missed it.

@lachlanjc you can add a label to the PR — if there's no label the bump will be from conventional commit prefixes — `"fix:"` and `"feat:"`. 

image

**Comment by LekoArts** [comment]
No worries, this can happen :)

**Pull request merged**
