### PR TITLE
docs(sx-prop): add more detail for responsive values.

### PR DESCRIPTION
**Pull request by PeterlitsZo**

### CODE REVIEW

**Review by lachlanjc — APPROVED** [review]
Appreciate the edit!

**Comment by PeterlitsZo** [comment]
Thanks.

**Comment by hasparus** [comment]
:rocket: PR was released in [`v0.14.0-develop.11`](https://github.com/system-ui/theme-ui/releases/tag/v0.14.0-develop.11) :rocket:

**Comment by hasparus** [comment]
:rocket: PR was released in [`v0.14.0`](https://github.com/system-ui/theme-ui/releases/tag/v0.14.0) :rocket:

**Comment by PeterlitsZo** [comment]
Wow!

**Pull request merged**
