### PR TITLE
Convert gatsby-theme-ui-layout to TypeScript

### PR DESCRIPTION
**Pull request by epilande**
Convert `gatsby-theme-ui-layout` to TypeScript.

Related to #668.

~Since this gets consumed as a Gatsby theme, I don't think it needs to be compiled.
I tested this out with `gatsby-theme-ui-blog` (which is still in JavaScript) and it works just like before 😃~

### CODE REVIEW

**Comment by mxstbr** [comment]
> Since this gets consumed as a Gatsby theme, I don't think it needs to be compiled.

Are Gatsby themes able to compile TypeScript? What if they use TypeScript options the package doesn't support? 🤔

**Comment by epilande** [comment]
> > Since this gets consumed as a Gatsby theme, I don't think it needs to be compiled.
> 
> Are Gatsby themes able to compile TypeScript? What if they use TypeScript options the package doesn't support? 🤔

**Comment by epilande** [comment]
@mxstbr oops I lied. I tried it out with a clean gatsby install and it didn’t work.. I thought it was magic :P

**Comment by jxnblk** [comment]
Sounds like it might make sense to leave the Gatsby plugins & themes in JS to avoid needing to compile them for the time being, right?

**Comment by epilande** [comment]
@jxnblk yeah, another option could be to set up gatsby-config with gatsby-plugin-typescript, though this package is bare bones and  that it might not be worth it

**Comment by jxnblk** [comment]
My guess is that it might not be worth it for the time being. One (small) nice thing about shipping the source code is that users can view more human-readable code in `node_modules`, which also is nice for some potential tooling we could build for shadowing (if that makes sense).

If Gatsby supports `.ts` in plugins/themes in the future, then I think it could make sense to convert these over.

**Comment by epilande** [comment]
Yeah 💯 agree. Closing for now

**Pull request closed without merging**
