### PR TITLE
Set up CodeSandbox CI

### LINKED ISSUE #1172: Use CodeSandbox CI
**Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

I'm always frustrated when I'm opening the CodeSandbox to reproduce a bug.
I'm also annoyed when I build tarballs of Theme UI packages to test it in my projects.

**Describe the solution you'd like**

[CodeSandbox CI](https://codesandbox.io/docs/ci) is quite rad. Maybe we can use it? It would also make testing new features more pleasant.

### PR DESCRIPTION
**Pull request by lachlanjc**
Closes #1172

### CODE REVIEW

**Comment by lachlanjc** [comment]
This actually works! Super cool service, thanks for spotting @hasparus. I configured it to spin up Gatsby & Next starters, feel free to tweak that & hit merge if you like.

**Review by hasparus — APPROVED** [review]
I love it!

**Comment by hasparus** [comment]
:rocket: PR was released in [`v0.14.0-develop.6`](https://github.com/system-ui/theme-ui/releases/tag/v0.14.0-develop.6) :rocket:

**Comment by hasparus** [comment]
:rocket: PR was released in [`v0.14.0`](https://github.com/system-ui/theme-ui/releases/tag/v0.14.0) :rocket:

**Pull request merged**
