### PR TITLE
fix(docs): Set text color on Demo page JSON code

### PR DESCRIPTION
**Pull request by appsparkler**
Currently in dark-mode; the color is not visible as it assumes the default color which is black.

# Version

Published prerelease version: `v0.12.2-develop.2`

<details>
  <summary>Changelog</summary>

  :tada: This release contains work from new contributors! :tada:
  
  Thanks for all your work!
  
  :heart: Akash ([@appsparkler](https://github.com/appsparkler))
  
  :heart: Greg Poole ([@gpoole](https://github.com/gpoole))
  
  #### 🐛 Bug Fix
  
  - fix(docs): Set text color on Demo page JSON code [#2024](https://github.com/system-ui/theme-ui/pull/2024) ([@appsparkler](https://github.com/appsparkler))
  
  #### 🏠 Internal
  
  - docs(pragma): add SWC instructions for Next.js [#2020](https://github.com/system-ui/theme-ui/pull/2020) ([@gpoole](https://github.com/gpoole))
  
  #### Authors: 2
  
  - Akash ([@appsparkler](https://github.com/appsparkler))
  - Greg Poole ([@gpoole](https://github.com/gpoole))
</details>

### CODE REVIEW

**Review by lachlanjc — APPROVED** [review]
Excellent fix, thank you for the contribution!

**Comment by hasparus** [comment]
:rocket: PR was released in [`v0.12.2-develop.2`](https://github.com/system-ui/theme-ui/releases/tag/v0.12.2-develop.2) :rocket:

**Comment by appsparkler** [comment]
> Excellent fix, thank you for the contribution!

@lachlanjc , the `Edit Page` link on the page made it very easy to do this.  Excellent architecture 👍

**Comment by hasparus** [comment]
:rocket: PR was released in [`v0.13.0`](https://github.com/system-ui/theme-ui/releases/tag/v0.13.0) :rocket:

**Pull request merged**
