### PR TITLE
Button hidden prop

### PR DESCRIPTION
**Pull request by atanasster**
Issue: #1254

Fix Button not respecting hidden prop

`<Button hidden>Click me</Button>`

### CODE REVIEW

**Review by lachlanjc — APPROVED** [review]
Looks great! Maybe add a test too so this doesn't break in the future? https://github.com/system-ui/theme-ui/blob/master/packages/components/test/index.js I don't have strong feelings about it.

**Comment by atanasster** [comment]
thanks @lachlanjc - great suggestion, I added a Button / hidden test

**Review by hasparus — APPROVED** [review]
Amazing!

**Comment by deckchairlabs** [comment]
Should this check be moved to Box, since all/most components would be affected by this?

**Comment by atanasster** [comment]
> Should this check be moved to Box, since all/most components would be affected by this?

Box and others actually work fine, since it doesnt set the display style. Afaics its only related to Button

**Comment by lachlanjc** [comment]
We should probably do a pass-through of other components if this is something we want to consistently support. I'd expect Grid & Flex don't work since they're setting `display` as well

**Comment by deckchairlabs** [comment]
From what I understand the `hidden` attribute is more semantic, for screen readers etc. So something all components should support in my opinion.

But that's probably best suited for a separate PR dealing with accessibility in general.

**Pull request merged**
