### PR TITLE
docs: re-order sidebar components into alphabetical order

### PR DESCRIPTION
**Pull request by thisislawatts**
I found myself using the Search functionality and Find in page frequently to locate a component. Alphabetical ordering would make this a little easier to use as a reference. 

✨ Great project.

### CODE REVIEW

**Comment by lachlanjc** [comment]
Works for me! Can we keep Variants up at the top since it's an important intro, then have the rest in alphabetical order?

**Review by hasparus — APPROVED** [review]
Nice one! Thanks 🙏

**Comment by hasparus** [comment]
:rocket: PR was released in [`v0.15.0-develop.6`](https://github.com/system-ui/theme-ui/releases/tag/v0.15.0-develop.6) :rocket:

**Comment by hasparus** [comment]
:rocket: PR was released in [`v0.15.0`](https://github.com/system-ui/theme-ui/releases/tag/v0.15.0) :rocket:

**Pull request merged**
