### PR TITLE
feat(docs): Algolia DocSearch integration

### LINKED ISSUE #1037: Add search to the docs (Algolia's DocSearch, maybe?)
**Is your feature request related to a problem? Please describe.**
Having a search thing in the docs would be awesome. Although by now I know where everything is, I remember when getting started with theme-ui, I had a hard time finding the things I was looking for.

**Describe the solution you'd like**
Algolia has a [specific solution for documentations](https://docsearch.algolia.com/), used by [React](https://reactjs.org/) and many other doc sites.

**Additional context**
I see that it's not so complicated to integrate, it's free, and would be an amazing improvement to the docs. I'd be happy to help with the integration!

### LINKED ISSUE #1099: Theme UI Documentation Search
**Is your feature request related to a problem? Please describe.**
I use theme-ui on daily basis on personal and work projects. The documentation is quite large and I just want to remember something that I used before so I navigate the whole docs to get it. 

Adding search in docs page will make it easy to remember things fast instead of navigating the documentation. 

**Describe the solution you'd like**
I don't have specific solution, may be any search engine like algolia!

### PR DESCRIPTION
**Pull request by atanasster**
Initializing the styles and scripts in gatsby-ssr and a search input box in the layout.

### CODE REVIEW

**Comment by lachlanjc** [comment]
Thank you so much for doing this! I'd love to take a pass on the design (it's making the "Theme UI" name wrap on my iPhone) before we merge but I super appreciate you getting this in place.

**Comment by atanasster** [comment]
Thanks, yes we will need to polish it - there are also some guides on styling the search box - we can make it to somewhat match the selected theme.

**Comment by hasparus** [comment]
I'm opting out of reviewing this due to limited throughput. Thanks for the PR, Atanas!

**Comment by lachlanjc** [comment]
Amazing. Can enable on mobile soon: contributions welcome!

**Pull request merged**
