### PR TITLE
css: Make background a theme-aware property

### LINKED ISSUE #2021: css: Make `background` a theme-aware property
**Is your feature request related to a problem? Please describe.**
I find it surprising and confusing that the `bg` shorthand can be set to a color name/key, but not `background`, as they read the same.

**Describe the solution you'd like**
I would like `background` to be a theme-aware property, so I can do `sx={{ background: 'myCustomColorName' }}`.

**Describe alternatives you've considered**
I can obviously use `bg` or `backgroundColor`. But once in a while, I may forget and use `background`, and be slightly annoyed when the color name I pass doesn’t get converted to the expected color value.

**Additional context**
I can send a PR for this if you (the maintainers) agree with the idea. Thank you!

### PR DESCRIPTION
**Pull request by lachlanjc**
Closes #2021 (perhaps fittingly!).

<details>
  <summary>📦 Published PR as canary version: <code>0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @theme-ui/color-modes@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  npm install @theme-ui/color@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  npm install @theme-ui/components@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  npm install @theme-ui/core@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  npm install @theme-ui/css@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  npm install @theme-ui/custom-properties@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  npm install @theme-ui/editor@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  npm install gatsby-plugin-theme-ui@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  npm install gatsby-theme-style-guide@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  npm install gatsby-theme-ui-layout@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  npm install @theme-ui/match-media@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  npm install @theme-ui/mdx@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  npm install @theme-ui/parse-props@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  npm install @theme-ui/preset-base@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  npm install @theme-ui/preset-bootstrap@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  npm install @theme-ui/preset-bulma@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  npm install @theme-ui/preset-dark@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  npm install @theme-ui/preset-deep@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  npm install @theme-ui/preset-funk@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  npm install @theme-ui/preset-future@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  npm install @theme-ui/preset-polaris@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  npm install @theme-ui/preset-roboto@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  npm install @theme-ui/preset-sketchy@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  npm install @theme-ui/preset-swiss@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  npm install @theme-ui/preset-system@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  npm install @theme-ui/preset-tailwind@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  npm install @theme-ui/preset-tosh@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  npm install @theme-ui/presets@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  npm install @theme-ui/prism@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  npm install @theme-ui/sidenav@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  npm install @theme-ui/style-guide@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  npm install @theme-ui/tailwind@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  npm install @theme-ui/theme-provider@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  npm install theme-ui@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  npm install @theme-ui/typography@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  # or 
  yarn add @theme-ui/color-modes@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  yarn add @theme-ui/color@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  yarn add @theme-ui/components@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  yarn add @theme-ui/core@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  yarn add @theme-ui/css@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  yarn add @theme-ui/custom-properties@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  yarn add @theme-ui/editor@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  yarn add gatsby-plugin-theme-ui@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  yarn add gatsby-theme-style-guide@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  yarn add gatsby-theme-ui-layout@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  yarn add @theme-ui/match-media@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  yarn add @theme-ui/mdx@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  yarn add @theme-ui/parse-props@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  yarn add @theme-ui/preset-base@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  yarn add @theme-ui/preset-bootstrap@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  yarn add @theme-ui/preset-bulma@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  yarn add @theme-ui/preset-dark@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  yarn add @theme-ui/preset-deep@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  yarn add @theme-ui/preset-funk@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  yarn add @theme-ui/preset-future@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  yarn add @theme-ui/preset-polaris@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  yarn add @theme-ui/preset-roboto@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  yarn add @theme-ui/preset-sketchy@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  yarn add @theme-ui/preset-swiss@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  yarn add @theme-ui/preset-system@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  yarn add @theme-ui/preset-tailwind@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  yarn add @theme-ui/preset-tosh@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  yarn add @theme-ui/presets@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  yarn add @theme-ui/prism@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  yarn add @theme-ui/sidenav@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  yarn add @theme-ui/style-guide@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  yarn add @theme-ui/tailwind@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  yarn add @theme-ui/theme-provider@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  yarn add theme-ui@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  yarn add @theme-ui/typography@0.13.1--canary.2056.3f06cb0b4ac9d2451cdbf616ad2cce65dbfd95bd.0
  ```
</details>

# Version

Published prerelease version: `v0.13.1-develop.7`

<details>
  <summary>Changelog</summary>

  #### 🐛 Bug Fix
  
  - fix(e2e): downgrade Cypress to 9.0.0 ([@hasparus](https://github.com/hasparus))
  - `@theme-ui/css`
    - css: Make background a theme-aware property [#2056](https://github.com/system-ui/theme-ui/pull/2056) ([@lachlanjc](https://github.com/lachlanjc))
  
  #### Authors: 3
  
  - Akash ([@appsparkler](https://github.com/appsparkler))
  - Lachlan Campbell ([@lachlanjc](https://github.com/lachlanjc))
  - Piotr Monwid-Olechnowicz ([@hasparus](https://github.com/hasparus))
</details>

### CODE REVIEW

**Comment by hasparus** [comment]
:rocket: PR was released in [`v0.13.1-develop.7`](https://github.com/system-ui/theme-ui/releases/tag/v0.13.1-develop.7) :rocket:

**Comment by hasparus** [comment]
:rocket: PR was released in [`v0.13.1`](https://github.com/system-ui/theme-ui/releases/tag/v0.13.1) :rocket:

**Comment by lachlanjc** [comment]
How can I make future PRs not show up as "Bug Fix" in the release notes?

**Comment by hasparus** [comment]
> How can I make future PRs not show up as "Bug Fix" in the release notes?

You can either prefix your commit with `feat(scope):` _or, I think, possibly_ add **enhancement** label to the PR.

**Pull request merged**
