### PR TITLE
(docs): Add Resources to sidebar

### LINKED ISSUE #751: Add related libraries in docs
**Is your feature request related to a problem? Please describe.**
As the community around theme-UI and system-UI grows it might be nice to have a page that links to related or companion libraries that use same theme specification or tie into the theme-UI ecosystem. 

**Additional context**
I have built a library Theme-UI-Native that is a port of the theme-UI library that works with React Native apps https://github.com/samjbmason/theme-ui-native

### LINKED ISSUE #1087: (docs) Add section for Theme UI component kits / themes
Thank you for Theme UI! ❤️

**Describe the solution you'd like**
We could grow the community by adding a section for related projects, such as component kits and themes based on Theme UI to the documentation.

**Additional context**
I believe it could grow the community when users like @atanasster and myself can share other works that extend Theme UI. Some pros I see are users can see examples of Theme UI usage in other work, they can find edge-cases that never will make it into Theme UI packages and it could motivate more people to contribute.

Examples:
- https://github.com/system-ui/theme-ui/discussions/1015

I can submit a pull request if this idea is considered good. I don't know if there should be some requirements, categorization of projects – or if this should just be a discussion topic?

### PR DESCRIPTION
**Pull request by cobraz**
fixes #1087
fixes #751

### CODE REVIEW

**Comment by jxnblk** [comment]
Thanks for the PR! I was imagining adding a dedicate page (in `packages/docs/src/pages`) so that others could easily contribute to the list and potentially include the description. The list will probably be fairly short right now, but I think that's okay. If you're up for it/have time, I think that'd be a good addition to the docs

**Comment by cobraz** [comment]
I totally agree! 👍 I’ll look into it tomorrow!

**Comment by lachlanjc** [comment]
Related: #1015

**Comment by cobraz** [comment]
If anyone was wondering, tomorrow eq ~ 1 - 10 days. 😅

The update contains a new page titled «Resources», description «Tools, themes, extensions and examples built by the Theme UI community.». I chose «Resources» instead of «Extensions», which seems to be a frequently used word to describe what we are trying to do.

Unsure if we'd like to stylize it differently?

### Reference resources
- https://angular.io/resources
- https://reactjs.org/community/external-resources.html

**Comment by cobraz** [comment]
@jxnblk Do you want any other changes? :)

**Comment by cobraz** [comment]
Maybe we should add https://github.com/cartolab-gis/elements to the list as well?

cc: @brambow

**Comment by LekoArts** [comment]
There's also https://github.com/system-ui/theme-ui/issues/697

**Pull request closed without merging**
