### PR TITLE
add types for css prop back

### LINKED ISSUE #1833: Types not available for css prop with @jsxImportSource theme-ui
**Describe the bug**
When I try using the `css=` prop in a file with jsxImportSource theme-ui set:

```tsx
/** @jsxImportSource theme-ui */
<div css={[ACTIVE_STYLE, ACTIVE_BADGE_STYLE]} />;
```

I get:

```
  Property 'css' does not exist on type 'ClassAttributes<HTMLDivElement> & HTMLAttributes<HTMLDivElement> & SxProp'.ts(2322)
```

This is mentioned as a valid use case in the docs: https://theme-ui.com/sx-prop#raw-css

**To Reproduce**
1. Create a new file with `/** @jsxImportSource theme-ui */`
2. Create a component with ```const TestComponent = () => <div css={css`display: block;`} />;```
3. TypeScript fails the type check

**Expected behavior**
`css=` should have a type definition present and typed to Emotion's css function output

**Additional context**
This was possible on version 0.3.2, and appears to still be supported in the docs. I am using theme-ui 0.9.1

### PR DESCRIPTION
**Pull request by hasparus**
Closes #1833.

- I added `css` prop to `sx` prop types, as Theme UI's `jsx` function calls Emotion's `jsx` function, and we have this documented in our docs.
- Prettier trolled me a bit. I mean, I'm not sure why `css/index.ts` wasn't formatted this way in the first place. I don't really like this diff, but I don't want to fight it.

<details>
  <summary>📦 Published PR as canary version: <code>0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0</code></summary>
  <br />
  
  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @theme-ui/color-modes@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  npm install @theme-ui/color@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  npm install @theme-ui/components@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  npm install @theme-ui/core@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  npm install @theme-ui/css@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  npm install @theme-ui/custom-properties@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  npm install @theme-ui/editor@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  npm install gatsby-plugin-theme-ui@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  npm install gatsby-theme-style-guide@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  npm install gatsby-theme-ui-layout@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  npm install @theme-ui/match-media@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  npm install @theme-ui/mdx@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  npm install @theme-ui/parse-props@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  npm install @theme-ui/preset-base@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  npm install @theme-ui/preset-bootstrap@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  npm install @theme-ui/preset-bulma@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  npm install @theme-ui/preset-dark@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  npm install @theme-ui/preset-deep@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  npm install @theme-ui/preset-funk@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  npm install @theme-ui/preset-future@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  npm install @theme-ui/preset-polaris@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  npm install @theme-ui/preset-roboto@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  npm install @theme-ui/preset-sketchy@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  npm install @theme-ui/preset-swiss@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  npm install @theme-ui/preset-system@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  npm install @theme-ui/preset-tailwind@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  npm install @theme-ui/preset-tosh@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  npm install @theme-ui/presets@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  npm install @theme-ui/prism@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  npm install @theme-ui/sidenav@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  npm install @theme-ui/style-guide@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  npm install @theme-ui/tachyons@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  npm install @theme-ui/tailwind@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  npm install @theme-ui/theme-provider@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  npm install theme-ui@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  npm install @theme-ui/typography@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  # or 
  yarn add @theme-ui/color-modes@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  yarn add @theme-ui/color@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  yarn add @theme-ui/components@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  yarn add @theme-ui/core@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  yarn add @theme-ui/css@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  yarn add @theme-ui/custom-properties@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  yarn add @theme-ui/editor@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  yarn add gatsby-plugin-theme-ui@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  yarn add gatsby-theme-style-guide@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  yarn add gatsby-theme-ui-layout@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  yarn add @theme-ui/match-media@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  yarn add @theme-ui/mdx@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  yarn add @theme-ui/parse-props@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  yarn add @theme-ui/preset-base@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  yarn add @theme-ui/preset-bootstrap@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  yarn add @theme-ui/preset-bulma@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  yarn add @theme-ui/preset-dark@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  yarn add @theme-ui/preset-deep@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  yarn add @theme-ui/preset-funk@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  yarn add @theme-ui/preset-future@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  yarn add @theme-ui/preset-polaris@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  yarn add @theme-ui/preset-roboto@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  yarn add @theme-ui/preset-sketchy@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  yarn add @theme-ui/preset-swiss@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  yarn add @theme-ui/preset-system@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  yarn add @theme-ui/preset-tailwind@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  yarn add @theme-ui/preset-tosh@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  yarn add @theme-ui/presets@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  yarn add @theme-ui/prism@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  yarn add @theme-ui/sidenav@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  yarn add @theme-ui/style-guide@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  yarn add @theme-ui/tachyons@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  yarn add @theme-ui/tailwind@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  yarn add @theme-ui/theme-provider@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  yarn add theme-ui@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  yarn add @theme-ui/typography@0.11.0-canary.1866.095ab5bd1ea54f6d6ce32a3d3fd85aa24f96ab27.0
  ```
</details>

# Version

Published prerelease version: `v0.11.0-develop.1`

<details>
  <summary>Changelog</summary>

  :tada: This release contains work from a new contributor! :tada:
  
  Thank you, Jordie Bodlay ([@jordie23](https://github.com/jordie23)), for all your work!
  
  #### 🚀 Enhancement
  
  - `@theme-ui/color-modes`, `@theme-ui/core`, `@theme-ui/editor`, `@theme-ui/theme-provider`, `theme-ui`
    - fix(color-modes): combine colors in nested providers [#1838](https://github.com/system-ui/theme-ui/pull/1838) ([@hasparus](https://github.com/hasparus))
  
  #### 🐛 Bug Fix
  
  - Update global-styles.mdx [#1858](https://github.com/system-ui/theme-ui/pull/1858) ([@jordie23](https://github.com/jordie23))
  - `@theme-ui/core`, `@theme-ui/css`
    - add types for css prop back [#1866](https://github.com/system-ui/theme-ui/pull/1866) ([@hasparus](https://github.com/hasparus))
  - `@theme-ui/color-modes`, `@theme-ui/components`, `@theme-ui/core`, `@theme-ui/editor`, `gatsby-theme-style-guide`, `gatsby-theme-ui-layout`, `@theme-ui/match-media`, `@theme-ui/mdx`, `@theme-ui/parse-props`, `@theme-ui/sidenav`, `@theme-ui/style-guide`, `@theme-ui/theme-provider`, `theme-ui`
    - 0.10 chores [#1842](https://github.com/system-ui/theme-ui/pull/1842) ([@hasparus](https://github.com/hasparus))
  
  #### 🏠 Internal
  
  - `theme-ui`
    - Setup Cypress [#1845](https://github.com/system-ui/theme-ui/pull/1845) ([@hasparus](https://github.com/hasparus))
  
  #### Authors: 2
  
  - Jordie Bodlay ([@jordie23](https://github.com/jordie23))
  - Piotr Monwid-Olechnowicz ([@hasparus](https://github.com/hasparus))
</details>

### CODE REVIEW

**Comment by lachlanjc** [comment]
This all looks great. Why do we want to expose the `css` prop though, instead of just `sx`?

**Review by fcisio — APPROVED** [review]

**Review by flo-sch — APPROVED** [review]

**Comment by hasparus** [comment]
> This all looks great. Why do we want to expose the css prop though, instead of just sx?

@lachlanjc We promised it in the docs, and I believe people are using it to work around the fact that `sx` doesn't accept an array. Previously, when both `sx` and `css` was defined globally, we didn't have to remember about `css` because Emotion defined it, but now, when the types are based on the JSX pragma configured you get `sx` OR `css`.

**Comment by hasparus** [comment]
:rocket: PR was released in [`v0.11.0-develop.1`](https://github.com/system-ui/theme-ui/releases/tag/v0.11.0-develop.1) :rocket:

**Comment by hasparus** [comment]
:rocket: PR was released in [`v0.11.0`](https://github.com/system-ui/theme-ui/releases/tag/v0.11.0) :rocket:

**Pull request merged**
