### PR TITLE
Release v0.13.2

### PR DESCRIPTION
**Pull request by hasparus**
You're welcome to press `[Merge]` when the tests pass, mate :)

<details>
  <summary>📦 Published PR as canary version: <code>0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @theme-ui/color-modes@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  npm install @theme-ui/color@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  npm install @theme-ui/components@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  npm install @theme-ui/core@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  npm install @theme-ui/css@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  npm install @theme-ui/custom-properties@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  npm install @theme-ui/editor@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  npm install gatsby-plugin-theme-ui@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  npm install gatsby-theme-style-guide@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  npm install gatsby-theme-ui-layout@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  npm install @theme-ui/match-media@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  npm install @theme-ui/mdx@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  npm install @theme-ui/parse-props@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  npm install @theme-ui/preset-base@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  npm install @theme-ui/preset-bootstrap@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  npm install @theme-ui/preset-bulma@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  npm install @theme-ui/preset-dark@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  npm install @theme-ui/preset-deep@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  npm install @theme-ui/preset-funk@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  npm install @theme-ui/preset-future@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  npm install @theme-ui/preset-polaris@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  npm install @theme-ui/preset-roboto@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  npm install @theme-ui/preset-sketchy@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  npm install @theme-ui/preset-swiss@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  npm install @theme-ui/preset-system@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  npm install @theme-ui/preset-tailwind@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  npm install @theme-ui/preset-tosh@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  npm install @theme-ui/presets@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  npm install @theme-ui/prism@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  npm install @theme-ui/sidenav@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  npm install @theme-ui/style-guide@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  npm install @theme-ui/tailwind@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  npm install @theme-ui/theme-provider@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  npm install theme-ui@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  npm install @theme-ui/typography@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  # or 
  yarn add @theme-ui/color-modes@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  yarn add @theme-ui/color@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  yarn add @theme-ui/components@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  yarn add @theme-ui/core@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  yarn add @theme-ui/css@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  yarn add @theme-ui/custom-properties@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  yarn add @theme-ui/editor@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  yarn add gatsby-plugin-theme-ui@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  yarn add gatsby-theme-style-guide@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  yarn add gatsby-theme-ui-layout@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  yarn add @theme-ui/match-media@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  yarn add @theme-ui/mdx@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  yarn add @theme-ui/parse-props@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  yarn add @theme-ui/preset-base@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  yarn add @theme-ui/preset-bootstrap@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  yarn add @theme-ui/preset-bulma@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  yarn add @theme-ui/preset-dark@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  yarn add @theme-ui/preset-deep@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  yarn add @theme-ui/preset-funk@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  yarn add @theme-ui/preset-future@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  yarn add @theme-ui/preset-polaris@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  yarn add @theme-ui/preset-roboto@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  yarn add @theme-ui/preset-sketchy@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  yarn add @theme-ui/preset-swiss@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  yarn add @theme-ui/preset-system@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  yarn add @theme-ui/preset-tailwind@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  yarn add @theme-ui/preset-tosh@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  yarn add @theme-ui/presets@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  yarn add @theme-ui/prism@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  yarn add @theme-ui/sidenav@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  yarn add @theme-ui/style-guide@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  yarn add @theme-ui/tailwind@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  yarn add @theme-ui/theme-provider@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  yarn add theme-ui@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  yarn add @theme-ui/typography@0.14.0--canary.2075.cae3c905a227ae45c9da571bba927d1c8d6997e1.0
  ```
</details>

### CODE REVIEW

**Comment by lachlanjc** [comment]
Can we include #2057 & #2058 or did you not want to?

**Comment by hasparus** [comment]
Just merged #2057. I think I'd group #2058 with @emotion/styled peer dep change in 0.14.

**Comment by lachlanjc** [comment]
Sounds great! I wish there was a way I could see the release notes & make any improvements here before publishing—am I missing anything?

**Comment by hasparus** [comment]
Hell, it didn't detect the release :> the `"patch"` label I added didn't seem to work (edit: did I add it?), and we didn't have any conventional comments with `fix:` nor `feat:` prefix. The docs are published though.

Here's the release log: https://github.com/system-ui/theme-ui/runs/4818753008?check_suite_focus=true

> I wish there was a way I could see the release notes & make any improvements here before publishing—am I missing anything?

What do you think about moving from Auto to Changesets?
They require some more manual work from maintainers and contributors, but we'd get more control.
It would require some work to make it work with allcontributors and canary releases, so I'm a little conflicted myself.

**Pull request merged**
