### PR TITLE
Add more Spinner components

### PR DESCRIPTION
**Pull request by alexpermyakov**
This is a test implementation for #583. There are so many great spinners, it would be great to be able to create new ones.

Demo:
spinners

### CODE REVIEW

**Comment by alexpermyakov** [comment]
I've added itemX/itemY prop functions along with the number of items and the animation props which allows us to implement pretty much any spinner.

**Things to clarify:**
1. What is better `<BarSpinner />` or <Spinner variant='bar' />? For the first one we still can apply the theme for changing colors/opacity: <BarSpinner variant='primary' />
2. Props vs Theme: while some props like _color_  should be a part of the theme, this is not really clear about _width/height_.
3. Where should we define animations? If we have a separate file for each spinner, it can be inside.
4. Do we need props like itemHeight/itemWidth? Even though it gives us some flexibility, it looks a bit excess. Instead the size of each spinner item might be relative to the size of the spinner itself. 
Probably we need width, height, duration props. Not sure about others.

**Comment by alexpermyakov** [comment]
Do we even need all these spinners @jxnblk? It's a bit more than just variants.

**Comment by alexpermyakov** [comment]
If these spinners make sense, I can polish them, apply variants, add a few more and update the doc, @jxnblk FYI.

**Comment by alexpermyakov** [comment]
Well, I'm not sure this implementation is fully aligned with theme-ui philosophy.
I can close this PR after getting some feedback.

**Comment by lachlanjc** [comment]
Your work here looks absolutely awesome, but yeah, I don't know that it makes sense to bundle them all directly. Either an extension package inside theme-ui or of course you could publish your own. Thoughts @jxnblk?

**Comment by alexpermyakov** [comment]
Maybe instead of actually creating all these spinners - we can update the doc and put these examples there.

**Comment by alexpermyakov** [comment]
Maybe it's a bit early days, should I close it @jxnblk?

**Comment by RishikeshDarandale** [comment]
Are you planning to add it back?

**Comment by lachlanjc** [comment]
@alexpermiakov It’d be awesome if you’re still interested in adding these to the docs!

**Pull request closed without merging**
