### PR TITLE
modernize Babel config

### PR DESCRIPTION
**Pull request by hasparus**
First commit of this PR hase the same configuration for `@babel/preset-env` Emotion uses (if I'm not wrong — [emotion/babel-preset-emotion-dev/src/index.js](https://github.com/emotion-js/emotion/blob/main/scripts/babel-preset-emotion-dev/src/index.js)).

Enabling `loose` resulted with 20% reduction in build size compared to current `develop`.

## Release notes

All Theme UI package became on average 34% lighter! 🪶 It's 9.5kB if you sum all of them!

The trade-off is, Babel config has changed and it no longer supports Internet Explorer 11. 
If you need to support legacy browsers, you can transpile node_modules (e.g. with [next-transpile-modules](https://github.com/martpie/next-transpile-modules)).

- [See build raport with size comparison for each package.](https://github.com/system-ui/theme-ui/runs/2618450614)
- [See updated Babel config.](https://github.com/system-ui/theme-ui/blob/develop/babel.config.js)

---

### Published prerelease version: `v0.9.0-develop.1`

<details>
  <summary>Changelog</summary>

  ### Release Notes
  
  #### modernize Babel config ([#1721](https://github.com/system-ui/theme-ui/pull/1721))
  
  All Theme UI package became on average 34% lighter! 🪶 It's 9.5kB if you sum all of them!
  
  The trade-off is, Babel config has changed and it no longer supports Internet Explorer 11. 
  If you need to support legacy browsers, you can transpile node_modules (e.g. with [next-transpile-modules](https://github.com/martpie/next-transpile-modules)).
  
  - [See build raport with size comparison for each package.](https://github.com/system-ui/theme-ui/runs/2618450614)
  - [See updated Babel config.](https://github.com/system-ui/theme-ui/blob/develop/babel.config.js)
  
  ---
  
  #### 🚀 Enhancement
  
  - `@theme-ui/preset-base`, `@theme-ui/preset-bootstrap`, `@theme-ui/sidenav`, `@theme-ui/typography`
    - modernize Babel config [#1721](https://github.com/system-ui/theme-ui/pull/1721) ([@hasparus](https://github.com/hasparus))
  
  #### 🐛 Bug Fix
  
  - Stop dependabot from trying to run codechecks [#1753](https://github.com/system-ui/theme-ui/pull/1753) ([@hasparus](https://github.com/hasparus))
  - fix(ci): add branches to codechecks ([@hasparus](https://github.com/hasparus))
  - ci: add codechecks with build-size-watcher [#1740](https://github.com/system-ui/theme-ui/pull/1740) ([@hasparus](https://github.com/hasparus))
  - `@theme-ui/components`
    - fix(components): set Select's bgColor to "background" - fixes dark mode ([@hasparus](https://github.com/hasparus))
  
  #### ⚠️ Pushed to `develop`
  
  - chore(auto): add omit-commits plugin ([@hasparus](https://github.com/hasparus))
  - ci(codechecks): remove debug env var ([@hasparus](https://github.com/hasparus))
  - ci(codechecks): remove patch ([@hasparus](https://github.com/hasparus))
  - ci(codechecks): use yml ([@hasparus](https://github.com/hasparus))
  - ci(codechecks): turn speculativeBranchSelection on ([@hasparus](https://github.com/hasparus))
  - ci(codechecks): another patch ([@hasparus](https://github.com/hasparus))
  - ci(codechecks): patch - yeah, it can only be done on develop ([@hasparus](https://github.com/hasparus))
  - ci(codechecks): patch ([@hasparus](https://github.com/hasparus))
  - ci(codechecks): debug ([@hasparus](https://github.com/hasparus))
  - ci(codechecks): make output verbose ([@hasparus](https://github.com/hasparus))
  - ci(codechecks): turn off speculative branch selection ([@hasparus](https://github.com/hasparus))
  - `@theme-ui/components`
    - test(components): update Select tests ([@hasparus](https://github.com/hasparus))
  
  #### 📝 Documentation
  
  - style DocSearch [#1714](https://github.com/system-ui/theme-ui/pull/1714) ([@atanasster](https://github.com/atanasster) [@hasparus](https://github.com/hasparus))
  
  #### Authors: 2
  
  - Atanas Stoyanov ([@atanasster](https://github.com/atanasster))
  - Piotr Monwid-Olechnowicz ([@hasparus](https://github.com/hasparus))
</details>

### CODE REVIEW

**Review by lachlanjc — APPROVED** [review]
I don't have a lot of experience with this, so not really sure, but go for it!

**Comment by hasparus** [comment]
lerna failed on canary release. Releasing so many packages is bit flaky, but this PR is a nice change to bundle size regardless. 

https://github.com/system-ui/theme-ui/pull/1721/checks?check_run_id=2617831975
image

**Comment by hasparus** [comment]
We're dropping almost 10 KB! @lachlanjc I'm almost ready to merge when you give it another look.

> Build Size — Change: -9.56KB (-33.94%) Total: 18.61KB

To-Do for this PR:

- [x] Test the canary in one of my projects
- [x] Write some [release notes](https://intuit.github.io/auto/docs/generated/changelog#additional-release-notes)

**Review by lachlanjc — APPROVED** [review]
Incredible! Let's do it

**Comment by hasparus** [comment]
:rocket: PR was released in [`v0.9.0-develop.1`](https://github.com/system-ui/theme-ui/releases/tag/v0.9.0-develop.1) :rocket:

**Comment by hasparus** [comment]
:rocket: PR was released in [`v0.9.0`](https://github.com/system-ui/theme-ui/releases/tag/v0.9.0) :rocket:

**Pull request merged**
