### PR TITLE
Improve documentation

### LINKED ISSUE #1876: Docs don't tell you to use ThemeProvider early enough.
**Describe the bug**
the color value can't be converted to real color
code:
image
product:
image

**To Reproduce**

1. yarn create next-app --ts
2. yarn add theme-ui
3. edit tsconfig.json, add this line
`"jsxImportSource": "theme-ui",`
4. create babel.config.js
```
module.exports = {
  presets: [
    [
      "next/babel",
      {
        "preset-react": {
          importSource: "theme-ui", // or '@theme-ui/core'
          runtime: "automatic",
          throwIfNamespace: false,
        },
      },
    ],
  ],
};
```

**demo**:
https://codesandbox.io/s/reverent-wright-q1u54?file=/src/pages/index.tsx:81-88

### PR DESCRIPTION
**Pull request by hasparus**
## What's inside?

- Moved the mention of ThemeProvider above the note about using Theme UI in Gatsby.
- Changed intro code snippets to TypeScript — they have **just one type**, and implementing a language toggle would take some time, so this should be passable for JS users.
- Expanded on readmes for `@theme-ui/css` and `@theme-ui/core`, and showed the readme for `@theme-ui/css` in the app.

Closes https://github.com/system-ui/theme-ui/issues/1876, I hope.

<details>
  <summary>📦 Published PR as canary version: <code>0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0</code></summary>
  <br />
  
  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @theme-ui/color-modes@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  npm install @theme-ui/color@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  npm install @theme-ui/components@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  npm install @theme-ui/core@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  npm install @theme-ui/css@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  npm install @theme-ui/custom-properties@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  npm install @theme-ui/editor@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  npm install gatsby-plugin-theme-ui@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  npm install gatsby-theme-style-guide@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  npm install gatsby-theme-ui-layout@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  npm install @theme-ui/match-media@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  npm install @theme-ui/mdx@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  npm install @theme-ui/parse-props@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  npm install @theme-ui/preset-base@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  npm install @theme-ui/preset-bootstrap@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  npm install @theme-ui/preset-bulma@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  npm install @theme-ui/preset-dark@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  npm install @theme-ui/preset-deep@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  npm install @theme-ui/preset-funk@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  npm install @theme-ui/preset-future@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  npm install @theme-ui/preset-polaris@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  npm install @theme-ui/preset-roboto@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  npm install @theme-ui/preset-sketchy@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  npm install @theme-ui/preset-swiss@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  npm install @theme-ui/preset-system@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  npm install @theme-ui/preset-tailwind@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  npm install @theme-ui/preset-tosh@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  npm install @theme-ui/presets@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  npm install @theme-ui/prism@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  npm install @theme-ui/sidenav@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  npm install @theme-ui/style-guide@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  npm install @theme-ui/tachyons@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  npm install @theme-ui/tailwind@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  npm install @theme-ui/theme-provider@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  npm install theme-ui@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  npm install @theme-ui/typography@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  # or 
  yarn add @theme-ui/color-modes@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  yarn add @theme-ui/color@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  yarn add @theme-ui/components@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  yarn add @theme-ui/core@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  yarn add @theme-ui/css@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  yarn add @theme-ui/custom-properties@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  yarn add @theme-ui/editor@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  yarn add gatsby-plugin-theme-ui@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  yarn add gatsby-theme-style-guide@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  yarn add gatsby-theme-ui-layout@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  yarn add @theme-ui/match-media@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  yarn add @theme-ui/mdx@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  yarn add @theme-ui/parse-props@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  yarn add @theme-ui/preset-base@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  yarn add @theme-ui/preset-bootstrap@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  yarn add @theme-ui/preset-bulma@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  yarn add @theme-ui/preset-dark@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  yarn add @theme-ui/preset-deep@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  yarn add @theme-ui/preset-funk@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  yarn add @theme-ui/preset-future@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  yarn add @theme-ui/preset-polaris@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  yarn add @theme-ui/preset-roboto@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  yarn add @theme-ui/preset-sketchy@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  yarn add @theme-ui/preset-swiss@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  yarn add @theme-ui/preset-system@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  yarn add @theme-ui/preset-tailwind@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  yarn add @theme-ui/preset-tosh@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  yarn add @theme-ui/presets@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  yarn add @theme-ui/prism@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  yarn add @theme-ui/sidenav@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  yarn add @theme-ui/style-guide@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  yarn add @theme-ui/tachyons@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  yarn add @theme-ui/tailwind@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  yarn add @theme-ui/theme-provider@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  yarn add theme-ui@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  yarn add @theme-ui/typography@0.11.0-canary.1877.9468a3809c2c39f70920eacac958a71b03651601.0
  ```
</details>

### CODE REVIEW

**Review by lachlanjc — APPROVED** [review]
Wow, thank you!! Big improvement.

**Comment by hasparus** [comment]
> Wow, thank you!! Big improvement.

Thank you!
Dude, I was wondering why people don't use `@theme-ui/core` in smaller projects where they don't need color modes and MDX. Turns out we barely documented it :D

**Comment by hasparus** [comment]
:rocket: PR was released in [`v0.11.0`](https://github.com/system-ui/theme-ui/releases/tag/v0.11.0) :rocket:

**Comment by hasparus** [comment]
:rocket: PR was released in [`v0.11.0`](https://github.com/system-ui/theme-ui/releases/tag/v0.11.0) :rocket:

**Comment by hasparus** [comment]
:rocket: PR was released in [`v0.11.0`](https://github.com/system-ui/theme-ui/releases/tag/v0.11.0) :rocket:

**Comment by hasparus** [comment]
:rocket: PR was released in [`v0.11.0`](https://github.com/system-ui/theme-ui/releases/tag/v0.11.0) :rocket:

**Comment by hasparus** [comment]
:rocket: PR was released in [`v0.11.2-develop.0`](https://github.com/system-ui/theme-ui/releases/tag/v0.11.2-develop.0) :rocket:

**Pull request merged**
