### PR TITLE
(docs) alphabetizes components list in sidebar

### PR DESCRIPTION
**Pull request by simpixelated**
I'm assuming a CHANGELOG update is not required, but happy to do so.

### CODE REVIEW

**Comment by lachlanjc** [comment]
Hmm. I’m cool either way but I actually love the order they’re in now—they’re grouped by category/how often you need them, so I can always find what I’m looking for there super fast instead of trying to think about what letters they use

**Comment by hasparus** [comment]
I'd probably stay with the current order. Variants and Box on the top just seem "logical", though I understand that this might be subjective.

**Comment by simpixelated** [comment]
I had though about leaving Variants at the top, since its not technically a component. Box would naturally remain near the top. I guess if the current order is working for people, it's not a problem. But as someone relatively new to the project, I find it difficult to see a logical pattern and end up scrolling up and down trying to find what I want.

**Comment by hasparus** [comment]
Hmm... maybe then

```
- Variants
- Box
- Everything else alphabetically
```

@lachlanjc what do think?

I feel that a search bar would be the solution to this problem.

Maybe we could group these components by "topic"? Layout, Typography, Form Controls, uhh others at the bottom? I'm not sure where would I put Embed.

**Comment by atanasster** [comment]
I agree by topic. Utilities at bottom with Embed + Portal, Keyboard, Responsive etc?

**Comment by lachlanjc** [comment]
Closing in favor of search (#1037)

**Pull request closed without merging**
