### PR TITLE
docs: Add section on vendor prefixes to object styles guide

### PR DESCRIPTION
**Pull request by lachlanjc**

### CODE REVIEW

**Review by hasparus — APPROVED** [review]
LGTM

**Comment by hasparus** [comment]
image

I'm wondering if we should mention vendor prefixed pseudo selectors.

**Comment by lachlanjc** [comment]
Do you mean like input placeholders? You just use those in strings, right?

**Comment by lachlanjc** [comment]
Since they work exactly like non-vendor-prefixed pseudo selectors, I'm cool with omitting for now. I'm going to merge & we can add more docs later, in the spirit of incremental correctness

**Pull request merged**
