### PR TITLE
Use backwards-compatible font stack for base theme

### PR DESCRIPTION
**Pull request by lachlanjc**
You may disagree with me on this since most sites will override this anyway, but I think our default system font stack should be more backwards-compatible. I not-infrequently run into browsers that don't yet support `system-ui` (like older versions of macOS, iOS <11), & there are other system fonts we can use. Browsers are & will continue adopting `system-ui`, but it's at 85% globally with no support on IE or Edge (https://caniuse.com/#feat=font-family-system-ui), & this is a simple fix.

### CODE REVIEW

**Comment by CanRau** [comment]
I, at least^^, totally agree as I always think about that when I stumble upon the font stack just without opening an issue 😅 👍

**Comment by jxnblk** [comment]
Thanks! I think this makes total sense from an ease-of-use standpoint. Would you mind updating the other presets that use the `system-ui` font stack?

**Comment by lachlanjc** [comment]
Done. Let me know if there's anywhere I shouldn't have changed—I mostly kept it off the docs site pages just for brevity but perhaps consistency is more important?

**Comment by jxnblk** [comment]
I think for docs, keeping the example font stack shorter is probably less distracting. Thanks for putting this together!! :shipit:

**Comment by jxnblk** [comment]
Looks like some snapshots are failing. Would you mind running `yarn test -u` to update those?

**Comment by lachlanjc** [comment]
Oops, sorry I forgot about that. Done!

**Pull request merged**
