### PR TITLE
Drop support for React 16 + 17

### PR DESCRIPTION
**Pull request by hasparus**
Hey @lachlanjc, I bumped `react`, `react-dom`, `react-test-renderer` and `@testing-library/react`, updated tests to use `act` properly (bcs they were failing after the update), and lifted React peer dependency to `>=18`.

I'd guess that by the time we release 0.15 most users shoulld already use React 18, and it would take a while for us to create a robust testing step to ensure compatibility with multiple React versions.

---

# Release Notes

Theme UI **0.15.0** drops support for React 16 and React 17. Your use case may still work, but we don't guarantee it. 

<details>
  <summary>📦 Published PR as canary version: <code>0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @theme-ui/color-modes@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  npm install @theme-ui/color@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  npm install @theme-ui/components@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  npm install @theme-ui/core@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  npm install @theme-ui/css@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  npm install @theme-ui/custom-properties@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  npm install @theme-ui/editor@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  npm install gatsby-plugin-theme-ui@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  npm install gatsby-theme-style-guide@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  npm install gatsby-theme-ui-layout@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  npm install @theme-ui/match-media@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  npm install @theme-ui/mdx@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  npm install @theme-ui/parse-props@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  npm install @theme-ui/preset-base@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  npm install @theme-ui/preset-bootstrap@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  npm install @theme-ui/preset-bulma@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  npm install @theme-ui/preset-dark@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  npm install @theme-ui/preset-deep@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  npm install @theme-ui/preset-funk@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  npm install @theme-ui/preset-future@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  npm install @theme-ui/preset-polaris@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  npm install @theme-ui/preset-roboto@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  npm install @theme-ui/preset-sketchy@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  npm install @theme-ui/preset-swiss@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  npm install @theme-ui/preset-system@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  npm install @theme-ui/preset-tailwind@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  npm install @theme-ui/preset-tosh@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  npm install @theme-ui/presets@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  npm install @theme-ui/prism@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  npm install @theme-ui/sidenav@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  npm install @theme-ui/style-guide@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  npm install @theme-ui/tailwind@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  npm install @theme-ui/theme-provider@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  npm install theme-ui@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  npm install @theme-ui/typography@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  # or 
  yarn add @theme-ui/color-modes@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  yarn add @theme-ui/color@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  yarn add @theme-ui/components@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  yarn add @theme-ui/core@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  yarn add @theme-ui/css@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  yarn add @theme-ui/custom-properties@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  yarn add @theme-ui/editor@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  yarn add gatsby-plugin-theme-ui@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  yarn add gatsby-theme-style-guide@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  yarn add gatsby-theme-ui-layout@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  yarn add @theme-ui/match-media@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  yarn add @theme-ui/mdx@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  yarn add @theme-ui/parse-props@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  yarn add @theme-ui/preset-base@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  yarn add @theme-ui/preset-bootstrap@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  yarn add @theme-ui/preset-bulma@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  yarn add @theme-ui/preset-dark@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  yarn add @theme-ui/preset-deep@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  yarn add @theme-ui/preset-funk@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  yarn add @theme-ui/preset-future@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  yarn add @theme-ui/preset-polaris@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  yarn add @theme-ui/preset-roboto@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  yarn add @theme-ui/preset-sketchy@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  yarn add @theme-ui/preset-swiss@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  yarn add @theme-ui/preset-system@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  yarn add @theme-ui/preset-tailwind@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  yarn add @theme-ui/preset-tosh@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  yarn add @theme-ui/presets@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  yarn add @theme-ui/prism@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  yarn add @theme-ui/sidenav@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  yarn add @theme-ui/style-guide@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  yarn add @theme-ui/tailwind@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  yarn add @theme-ui/theme-provider@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  yarn add theme-ui@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  yarn add @theme-ui/typography@0.15.0--canary.2215.208e019b1ec6fb2203209b11c915e5a1587551ed.0
  ```
</details>

# Version

Published prerelease version: `v0.15.0-develop.0`

<details>
  <summary>Changelog</summary>

  ### Release Notes
  
  #### Drop support for React 18 ([#2215](https://github.com/system-ui/theme-ui/pull/2215))
  
  Theme UI **0.15.0** drops support for React 16 and React 17. Your use case may still work, but we don't guarantee it.
  
  ---
  
  #### 🚀 Enhancement
  
  - `@theme-ui/color-modes`, `@theme-ui/components`, `@theme-ui/core`, `@theme-ui/editor`, `gatsby-plugin-theme-ui`, `gatsby-theme-style-guide`, `gatsby-theme-ui-layout`, `@theme-ui/match-media`, `@theme-ui/mdx`, `@theme-ui/parse-props`, `@theme-ui/preset-base`, `@theme-ui/preset-bootstrap`, `@theme-ui/preset-bulma`, `@theme-ui/preset-dark`, `@theme-ui/preset-deep`, `@theme-ui/preset-funk`, `@theme-ui/preset-polaris`, `@theme-ui/preset-roboto`, `@theme-ui/preset-swiss`, `@theme-ui/preset-system`, `@theme-ui/preset-tailwind`, `@theme-ui/preset-tosh`, `@theme-ui/prism`, `@theme-ui/sidenav`, `@theme-ui/style-guide`, `@theme-ui/theme-provider`, `theme-ui`
    - Drop support for React 18 [#2215](https://github.com/system-ui/theme-ui/pull/2215) ([@hasparus](https://github.com/hasparus))
  
  #### 🐛 Bug Fix
  
  - `gatsby-plugin-theme-ui`
    - fix(gatsby-plugin-theme-ui): Stop using JSX in gatsby-browser.js and gatsby-ssr.js ([@hasparus](https://github.com/hasparus))
  
  #### Authors: 1
  
  - Piotr Monwid-Olechnowicz ([@hasparus](https://github.com/hasparus))
</details>

### CODE REVIEW

**Comment by hasparus** [comment]
Stopping Vercel and e2e tests, because docs build hangs.

**Comment by hasparus** [comment]
:rocket: PR was released in [`v0.15.0-develop.0`](https://github.com/system-ui/theme-ui/releases/tag/v0.15.0-develop.0) :rocket:

**Comment by lachlanjc** [comment]
Makes sense to me!

**Comment by hasparus** [comment]
image

Oh god, I'm a king of PR titles it seems. Thanks!

**Comment by hasparus** [comment]
:rocket: PR was released in [`v0.15.0`](https://github.com/system-ui/theme-ui/releases/tag/v0.15.0) :rocket:

**Pull request merged**
