### PR TITLE
WIP: Move figma-theme package to Theme UI

### PR DESCRIPTION
**Pull request by jxnblk**
The [figma-theme](https://github.com/jxnblk/figma-theme) package hasn't been touched in a while, but it's the sort of library that would fit in well with Theme UI. It needs a few updates to conform to the latest thinking around the theme specification, and it'd be great to get some help from folks who use Figma to test this out

**To do**

- [ ] Consider whether `superstruct` is worth using or if it's better to start the `@theme-ui/schema` package
- [ ] Ensure tests run with Jest and the setup in this repo
- [ ] Update the theme schema, especially wrt the typography styles
- [ ] Consider populating `theme.styles` with Figma API data
- [ ] Look into the Figma API to see if anything new is available for use
- [ ] Deprecate the original `figma-theme` package once this is published

### CODE REVIEW

**Comment by braposo** [comment]
I'll have a proper look at this next week, just wanted to put it in writing so I get public accountability 😬😅

**Comment by braposo** [comment]
@jxnblk first all of sorry I really didn't pickup on this before, but I'm sure you understand that life gets in the way quite often.

I actually did some preliminar work by creating the https://github.com/braposo/figma-transformer library that makes the process of extracting information from Figma much easier (in my opinion) and was thinking about applying that here.

However, in the meantime @siddharthkp has created https://github.com/ds-tools/theme.figma which uses my library (thanks!) and (I think) fits into what you were thinking here.

Just wanted to start the conversation and see if there's anything that makes sense doing.

Thanks!

**Comment by jxnblk** [comment]
@braposo no worries at all! This is an open source project, so don't feel any pressure to contribute, but we'd still love any help we can get :)

As far as this particular PR goes, I am completely okay with ditching some or all of the code here for a working implementation. I'll try to take a look at what you and @siddharthkp have already, but also feel free to open a PR or another issue in the meantime

**Comment by jxnblk** [comment]
Closing this out since it's been a while. If anyone wants to take a stab at adding a Figma plugin, feel free to open a new PR

**Pull request closed without merging**
