### PR TITLE
Enable highlight lines

### PR DESCRIPTION
**Pull request by laurieontech**
This PR supports line highlighting in prism code blocks.

Specifically, // highlight-line and // highligh-start (or end).

The README is updated and all (save for theme-ui) presets are given a highlight default style. This also handles a handful of snapshot tests to validate this behavior.

### CODE REVIEW

**Comment by jxnblk** [comment]
Canary version published with the `@highlight` tag

**Comment by hasparus** [comment]
I just merged #805. I'll help you out with any conflicts I just made if it's okay.

**Comment by laurieontech** [comment]
Thanks @hasparus, that'd be great.

**Comment by hasparus** [comment]
> warning package.json: "dependencies" has dependency "@types/color" with range "3.0.1" that collides with a dependency in "devDependencies" of the same name with version "^3.0.1"

It's super weird the build failed on Netlify, but not in Actions.

**Pull request merged**
