### PR TITLE
v0.3

### PR DESCRIPTION
**Pull request by jxnblk**
This contains some small breaking changes. Be sure to follow the migration guide when updating from 0.2.x to 0.3.

Install prerelease with: `npm i theme-ui@next`

## Changes

- Splits main package into `@theme-ui/core`, `@theme-ui/mdx`, and `@theme-ui/color-modes`
- Removes layout components
- Removes stateful theme
- Includes `@theme-ui/components` in main `theme-ui` package
- Removes internal `styled` implementation in favor of `@emotion/styled`
- Removes `ThemeStateProvider` component

## Breaking

- Theme UI context no longer includes `components`. Use the official MDX `useMDXComponents` hook if you are directly accessing components via context.
- Layout components have been deprecated. Replace `Layout`, `Header`, `Main`, and `Footer` with `Box` or `Flex` components if needed.
- ~~When CSS custom properties are enabled, raw color values are no longer provided from the context hook. Use the new `theme.rawColors` object if you need to access raw color values.~~
- The theming context is now stateless. If you are using the `context.setTheme` method, this no longer works.

## To do

- [ ] Merge #502
- [x] Add default body margin reset
- [x] Consider global `box-sizing` defaults #578
- [x] Add migration guide
- [x] Ensure documentation is updated              
- [x] Fix customize page in docs
- [x] Test module resolutions with Yarn
- [x] Update `execa` dependency in packages
- [x] Update READMEs               
- [x] Test treeshaking
- [x] Fix `@theme-ui/editor` package & provide stateful theme API
- [x] Publish prerelease
- [x] Ensure `@theme-ui/color` API works as expected
- [x] Default body colors #223 
- [x] Option for global typographic styles #466
- [x] Resolve issue with `<del>` #401

### CODE REVIEW

**Comment by lachlanjc** [comment]
This looks so amazing. What’s the timeline on launch?

**Comment by lachlanjc** [comment]
This looks so amazing. What’s the timeline on launch?

One small thing—since the package is now integrated, I think it makes sense to add an example of Components to the README now, alongside [the `sx` prop](https://github.com/system-ui/theme-ui/tree/next-core-mdx#sx-prop), so people know the custom JSX pragma isn’t the only way to use Theme UI.

**Comment by t2ca** [comment]
Any idea why i'm getting this error after upgrade to v0.3

thanks

```
 ERROR #10226  CONFIG

Couldn't find the "gatsby-plugin-theme-ui" plugin declared in "/Projects/gatsby-themes/gatsby-theme-t2/gatsby-theme-showcase/gatsby-config.js".
```

**Comment by jxnblk** [comment]
@lachlanjc that's a great idea! I think it'd be okay to update the docs after this is merged since that wouldn't mean a breaking change

**Comment by jxnblk** [comment]
@t2ca can you verify that `gatsby-plugin-theme-ui` is installed locally?

**Comment by t2ca** [comment]
> @t2ca can you verify that `gatsby-plugin-theme-ui` is installed locally?

Thank you! This fixed the problem.  I had `gatsby-plugin-theme-ui` installed in my theme only.

**Comment by t2ca** [comment]
Sorry to bother you again, Im stuck on this error, would appreciate some direction to fix this.

`Error: [useColorMode] requires the ColorModeProvider component`

**Comment by lachlanjc** [comment]
Can you share a repo @t2ca? Also check that you’re running the latest versions—`ColorModeProvider` was [deprecated in May](https://github.com/system-ui/theme-ui/pull/30#issue-281817722).

**Comment by t2ca** [comment]
> Can you share a repo @t2ca? Also check that you’re running the latest versions—`ColorModeProvider` was [deprecated in May](https://github.com/system-ui/theme-ui/pull/30#issue-281817722).

Thank you, I didn't have the latest version on a couple packages. Everything is working again!

**Pull request merged**
